
'use client';

import { useState } from 'react';
import { Button } from "@/components/ui/button";
import { CreditCard, Loader2, RefreshCw } from "lucide-react";
import { toast } from "@/hooks/use-toast";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { useRouter } from 'next/navigation';

interface PaystackDepositProps {
  userEmail: string;
  userId: string;
}

export default function PaystackDeposit({ userEmail, userId }: PaystackDepositProps) {
  const [amount, setAmount] = useState('');
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [loading, setLoading] = useState(false);
  const router = useRouter();

  const handleFundWallet = async () => {
    const parsedAmount = parseFloat(amount);
    if (isNaN(parsedAmount) || parsedAmount < 5) {
      toast({ title: "Invalid Amount", description: "Minimum deposit is GHS 5.", variant: "destructive" });
      return;
    }
    if (parsedAmount > 500) {
      toast({ title: "Limit Exceeded", description: "Maximum single deposit is GHS 500.", variant: "destructive" });
      return;
    }

    setLoading(true);
    try {
      // 1. Initialize on our server to create the pending transaction record
      const initResponse = await fetch('/api/paystack/initialize', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          amount: parsedAmount,
          email: userEmail,
          userId: userId
        }),
      });

      const initData = await initResponse.json();

      if (!initData.reference) {
        throw new Error(initData.error || 'Failed to initialize payment');
      }

      // 2. Load Paystack Inline and open the popup
      // Using dynamic import for the browser-only package
      const PaystackPop = (await import('@paystack/inline-js')).default;
      const paystack = new PaystackPop();
      
      paystack.newTransaction({
        key: process.env.NEXT_PUBLIC_PAYSTACK_PUBLIC_KEY!,
        email: userEmail,
        amount: Math.round(parsedAmount * 100), // Paystack expects Pesewas
        currency: 'GHS',
        ref: initData.reference, // Use the reference generated by our server
        onSuccess: (transaction: any) => {
          setIsDialogOpen(false);
          setLoading(false);
          toast({ title: "Payment Successful", description: "Verifying transaction..." });
          // 3. Redirect to our verification page with the reference
          router.push(`/payment/verify?reference=${transaction.reference}`);
        },
        onCancel: () => {
          setLoading(false);
          toast({ title: "Cancelled", description: "Payment was cancelled." });
        },
        metadata: {
          custom_fields: [
            {
              display_name: "User ID",
              variable_name: "user_id",
              value: userId
            }
          ]
        }
      });

    } catch (err: any) {
      console.error(err);
      toast({ 
        title: "Payment Error", 
        description: err.message || "Could not start payment process.", 
        variant: "destructive" 
      });
      setLoading(false);
    }
  };

  return (
    <Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
      <DialogTrigger asChild>
        <Button className="w-full gap-2 font-semibold shadow-lg shadow-primary/20">
          <RefreshCw className="w-4 h-4" /> Fund Wallet
        </Button>
      </DialogTrigger>
      <DialogContent className="sm:max-w-[425px] bg-card border-white/5">
        <DialogHeader>
          <DialogTitle>Fund Your Wallet</DialogTitle>
          <DialogDescription>
            Enter the amount to deposit (GHS 5 - 500).
          </DialogDescription>
        </DialogHeader>
        <div className="grid gap-4 py-4">
          <div className="grid gap-2">
            <Label htmlFor="amount" className="text-xs uppercase font-bold text-muted-foreground">Amount (GHS)</Label>
            <Input
              id="amount"
              type="number"
              placeholder="20.00"
              min="5"
              max="500"
              className="bg-background/50 border-white/5 h-12 text-lg font-bold"
              value={amount}
              onChange={(e) => setAmount(e.target.value)}
            />
          </div>
        </div>
        <DialogFooter>
          <Button 
            onClick={handleFundWallet} 
            className="w-full h-12 font-bold text-lg"
            disabled={loading}
          >
            {loading ? <Loader2 className="animate-spin mr-2" /> : <CreditCard className="w-5 h-5 mr-2" />}
            {loading ? 'OPENING POPUP...' : 'PROCEED TO PAY'}
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
